name: uni_kit
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  provider:
  http:
  html:
  flutter_datetime_picker: ^1.2.8
  flutter_staggered_grid_view: ^0.3.0
  hive:
  hive_flutter:
  path_provider:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  hive_generator:
  build_runner:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  fonts:
    - family: Galano
      fonts:
        - asset: assets/fonts/GalanoGrotesqueDEMO-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          style: italic

flutter_icons:
  android: "launcher_icon" 
  image_path: "assets/icon/icon.png"
