name: uni_kit
description: Emergency Kit for hocams

version: 1.0.33+33

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  url_launcher: ^5.4.1
  progress_indicators: ^0.1.4
  provider: ^4.0.0
  http:
  html:
  flutter_datetime_picker: ^1.2.8
  flutter_staggered_grid_view: ^0.3.0
  hive: ^1.2.0
  hive_flutter:
  path_provider:
  flutter_local_notifications: ^1.1.1
  # Check that you have this dependency (added in the previous step)
  firebase_core: ^0.4.0+9

  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.2

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  # firebase_auth: ^0.14.0+5
  # cloud_firestore: ^0.12.9+5

  flutter:
    sdk: flutter
  
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  hive_generator:
  build_runner:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
   - assets/ring_routes/

  fonts:
    - family: Galano
      fonts:
        - asset: assets/fonts/GalanoGrotesqueDEMO-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          style: italic

flutter_icons:
  android: "launcher_icon" 
  image_path: "assets/icon/icon.png"
